### ISSUE TITLE
Not running in my pc please help

### ISSUE THREAD

**Issue by Mahesh0253** [cyberboysumanjay/Gdrivedownloader#1]
I tried to run but it gives me error-

python gdrive_upload.py
Enter the Direct URL of the file you want to download:
http://sumanjay.ooo/img/jetpacktocat.jpg
Beginning file download...
This may take time depending upon the file size.
Please be patient
Error! Can't proceed further.
Sorry!
[WinError 2] The system cannot find the file specified
[Errno 2] No such file or directory: 'jetpacktocat.jpg'

**Comment by cyberboysumanjay** [comment]
I guess the problem is occurring because you're using Windows and script is unable to find wget while running subprocess command. I have pushed a commit to use wget as a python module instead of subprocess. Make sure you install the requirements again before executing script.
This should fix your issue. 
Report if it worked for you!

**Comment by Mahesh0253** [comment]
Now it perfectly working thanks !
But how deploy it on Heroku, I tried but it gives error

**Comment by cyberboysumanjay** [comment]
This is a script made to work in command line. If you want to deploy it on Heroku you have to use this in a web app and deploy it accordingly. Flask or Django will be helpful for you.

**Comment by innowebka** [comment]
so it does download to local and then upload to your drive  ?

**Comment by Mahesh0253** [comment]
Yes

**Comment by Mahesh0253** [comment]
> so it does download to local and then upload to your drive ?

Yes
